# Generated by Django 5.1.1 on 2024-11-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller',
            field=models.BooleanField(default=False),
        ),
    ]
