# Generated by Django 5.1.1 on 2024-10-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
    ]
