# Generated by Django 5.1.1 on 2024-10-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['pk', 'paid']},
        ),
    ]
