# Generated by Django 5.1.1 on 2024-11-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_order_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=250, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
