# Generated by Django 5.1.1 on 2024-11-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_stripeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeorder',
            name='date_ordered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
