# Generated by Django 5.1.1 on 2024-11-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_stripeorder_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.order'),
        ),
    ]
